version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11
        environment:
          DATABASE_URL: postgresql://postgres@localhost/circle_test
      - image: cimg/postgres:14.8
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "webapp/requirements.txt" }}-{{ checksum "tests/requirements.txt" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install -r webapp/requirements.txt
            pip install -r tests/requirements.txt
            pip install pylint pytest
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "webapp/requirements.txt" }}-{{ checksum "tests/requirements.txt" }}
      - run:
          name: Run pylint
          command: |
            . venv/bin/activate
            pylint webapp
            pylint tests
      - run:
          name: Check for webapp changes
          command: |
            git diff --quiet HEAD^ HEAD webapp || echo "export WEBAPP_CHANGED=true" >> $BASH_ENV
      - run:
          name: Run pytest
          command: |
            . venv/bin/activate
            if [ "$WEBAPP_CHANGED" = "true" ]; then
              pytest tests
            else
              echo "No changes in webapp, skipping pytest for webapp"
            fi

workflows:
  build_and_test:
    jobs:
      - build
